"use client"

import { motion } from "framer-motion"
import { UserPlus, ClipboardCheck, Dumbbell, TrendingUp } from "lucide-react"

const steps = [
  {
    icon: UserPlus,
    step: "01",
    title: "Create Your Profile",
    description:
      "Sign up and tell us about your fitness goals, dietary preferences, and current health status.",
  },
  {
    icon: ClipboardCheck,
    step: "02",
    title: "Complete Health Assessment",
    description:
      "Take our AI-driven health assessment to get your BMI analysis, health score, and personalized recommendations.",
  },
  {
    icon: Dumbbell,
    step: "03",
    title: "Follow Your AI Plan",
    description:
      "Get personalized workout routines and nutrition plans generated by AI based on your unique profile.",
  },
  {
    icon: TrendingUp,
    step: "04",
    title: "Track & Achieve",
    description:
      "Log your progress, earn achievements, unlock charity donations, and let AROMI guide you to your goals.",
  },
]

export function HowItWorks() {
  return (
    <section
      id="how-it-works"
      className="border-y border-border bg-muted/30 px-6 py-24 md:py-32"
    >
      <div className="mx-auto max-w-7xl">
        <div className="mb-16 text-center">
          <p className="mb-3 text-sm font-medium uppercase tracking-wider text-primary">
            How It Works
          </p>
          <h2 className="text-balance font-display text-3xl font-bold text-foreground md:text-4xl">
            Your Wellness Journey in 4 Steps
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-pretty text-muted-foreground">
            Getting started with ArogyaMitra is simple. Our AI handles the
            complexity so you can focus on your health.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
          {steps.map((item, index) => (
            <motion.div
              key={item.step}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
              className="relative flex flex-col items-center text-center"
            >
              <div className="relative mb-6">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary text-primary-foreground">
                  <item.icon className="h-7 w-7" />
                </div>
                <span className="absolute -right-2 -top-2 flex h-7 w-7 items-center justify-center rounded-full bg-accent text-xs font-bold text-accent-foreground">
                  {item.step}
                </span>
              </div>
              <h3 className="mb-2 font-display text-lg font-semibold text-foreground">
                {item.title}
              </h3>
              <p className="text-sm leading-relaxed text-muted-foreground">
                {item.description}
              </p>
              {index < steps.length - 1 && (
                <div className="absolute right-0 top-8 hidden h-px w-[calc(100%-4rem)] translate-x-1/2 bg-border lg:block" />
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
